# Generated by Django 4.2.4 on 2023-08-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
